# Generated by Django 4.1.4 on 2022-12-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Feedback', models.TextField(default='the service is good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaOrder.pizzaorder')),
            ],
        ),
    ]
